{"uuid": "04970679-0f11-4001-a86b-d0c8a9186b19", "children": ["e3c738e2-a2f4-4281-a720-c27619ce4874"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1720636316397, "stop": 1720636316397}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'node'\n", "trace": "  File \"C:\\Users\\rjman\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rjman\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 896, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Python\\python-workspace-pycharm\\SeleniumPythonHybridFramework\\tests\\conftest.py\", line 15, in log_on_failure\n    method_name = item.node.name\n                  ^^^^^^^^^\n"}, "start": 1720636316789, "stop": 1720636316790}], "start": 1720636316397, "stop": 1720636316790}