{"uuid": "3ec95765-e4e5-4e70-b4d7-56fbd8fea328", "children": ["27377262-484a-4de0-a381-39122a6edfd3"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1720636251420, "stop": 1720636251420}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'node'\n", "trace": "  File \"C:\\Users\\rjman\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rjman\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 896, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Python\\python-workspace-pycharm\\SeleniumPythonHybridFramework\\tests\\conftest.py\", line 15, in log_on_failure\n    method_name = item.node.name\n                  ^^^^^^^^^\n"}, "start": 1720636256165, "stop": 1720636256436}], "start": 1720636251420, "stop": 1720636256436}